package main

import (
	"fmt"
	"slices"
	"strings"

	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/discovery"
	"k8s.io/client-go/rest"
)

var autoGeneratedField = map[string]bool{
	"creationTimestamp": true,
	"resourceVersion":   true,
	"generation":        true,
	"uid":               true,
	"managedFields":     true,
	"selfLink":          true,
	"status":            true, // skip whole status subtree
}

// A placeholder for referring version (-v)
var version = "v1.0.0"

func resolveGVR(config *rest.Config, input string) (schema.GroupVersionResource, bool, error) {
	discoveryClient, err := discovery.NewDiscoveryClientForConfig(config)
	if err != nil {
		return schema.GroupVersionResource{}, false, err
	}

	resources, err := discoveryClient.ServerPreferredResources()
	if err != nil {
		return schema.GroupVersionResource{}, false, err
	}

	input = strings.ToLower(input)

	for _, resource := range resources {
		gv, err := schema.ParseGroupVersion(resource.GroupVersion)
		if err != nil {
			continue
		}

		for _, r := range resource.APIResources {
			name       := strings.ToLower(r.Name) // plural
			kind       := strings.ToLower(r.Kind)
			shortNames := r.ShortNames

			full := name
			if gv.Group != "" {
				full = name + "." + gv.Group
			}

														// Match cases:
			if input == name ||     					// networkpolicies
				slices.Contains(shortNames, input) || 	// netpol
				input == kind ||    					// networkpolicy
				input == full {     					// networkpolicies.networking.k8s.io
				return schema.GroupVersionResource{
					Group:    gv.Group,
					Version:  gv.Version,
					Resource: r.Name,
				}, r.Namespaced, nil
			}
		}
	}

	return schema.GroupVersionResource{}, false, fmt.Errorf("resource not found: %s", input)
}

func matchGrep(val string) bool {
	if grep == "" {
		return true
	}
	return strings.Contains(val, grep)
}

func findKey(val string) bool {
	if find == "" {
		return true
	}
	return strings.Contains(val, find)
}

func joinPath(path []string) string {
    return strings.Join(path, ".")
}