package main

import (
	"fmt"
	"slices"
	"strings"

	"gopkg.in/yaml.v3"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/discovery"
	"k8s.io/client-go/rest"
)

var autoGeneratedField = map[string]bool{
	"kubectl.kubernetes.io/last-applied-configuration": true,
	"containerID":       true,
	"creationTimestamp": true,
	"generation":        true,
	"managedFields":     true,
	"resourceVersion":   true,
	"selfLink":          true,
	"status":            true, // skip whole status subtree
	"uid":               true,
}

// A placeholder for referring version (-v)
var version = "v1.0.0"

func resolveGVR(config *rest.Config, input string) (schema.GroupVersionResource, bool, error) {
	discoveryClient, err := discovery.NewDiscoveryClientForConfig(config)
	if err != nil {
		return schema.GroupVersionResource{}, false, err
	}

	resources, err := discoveryClient.ServerPreferredResources()
	if err != nil {
		return schema.GroupVersionResource{}, false, err
	}

	input = strings.ToLower(input)

	for _, resource := range resources {
		gv, err := schema.ParseGroupVersion(resource.GroupVersion)
		if err != nil {
			continue
		}

		for _, r := range resource.APIResources {
			name := strings.ToLower(r.Name) // plural
			kind := strings.ToLower(r.Kind)
			shortNames := r.ShortNames

			full := name
			if gv.Group != "" {
				full = name + "." + gv.Group
			}

			// Match cases:
			if input == name || // networkpolicies
				slices.Contains(shortNames, input) || // netpol
				input == kind || // networkpolicy
				input == full { // networkpolicies.networking.k8s.io
				return schema.GroupVersionResource{
					Group:    gv.Group,
					Version:  gv.Version,
					Resource: r.Name,
				}, r.Namespaced, nil
			}
		}
	}

	return schema.GroupVersionResource{}, false, fmt.Errorf("resource not found: %s", input)
}

// return the prefix used to identify a Kubernetes resource when multiple resources
func resourcePrefix(node *yaml.Node) []string {
	if node == nil || node.Kind != yaml.MappingNode {
		return nil
	}

	kindNode := getMapValue(node, "kind")
	if kindNode == nil || kindNode.Kind != yaml.ScalarNode {
		return nil
	}

	metadataNode := getMapValue(node, "metadata")
	if metadataNode == nil || metadataNode.Kind != yaml.MappingNode {
		return nil
	}

	nameNode := getMapValue(metadataNode, "name")
	if nameNode == nil || nameNode.Kind != yaml.ScalarNode {
		return nil
	}

	kind := strings.ToLower(strings.TrimSpace(kindNode.Value))
	name := strings.ToLower(strings.TrimSpace(nameNode.Value))

	if kind == "" || name == "" {
		return nil
	}

	return []string{kind, name}
}

// return the individual resource nodes contained in a Kubernetes List object
func expandListNode(node *yaml.Node) []*yaml.Node {
	if node == nil || node.Kind != yaml.MappingNode {
		return []*yaml.Node{node}
	}

	kindNode := getMapValue(node, "kind")

	// Resource is not a Kubernetes List
	if kindNode == nil || kindNode.Value != "List" {
		return []*yaml.Node{node}
	}

	itemsNode := getMapValue(node, "items")

	// A List without items is still a single node
	if itemsNode == nil || itemsNode.Kind != yaml.SequenceNode {
		return []*yaml.Node{node}
	}

	return itemsNode.Content
}

// expand the Kubernets List object before applying kind.name prefix
func expandListNodes(nodes []*yaml.Node) []*yaml.Node {
	var resources []*yaml.Node

	for _, node := range nodes {
		resources = append(resources, expandListNode(node)...)
	}

	return resources
}

func matchGrep(val string) bool {
	if grep == "" {
		return true
	}
	return strings.Contains(val, grep)
}

func findKey(val string) bool {
	if find == "" {
		return true
	}
	return strings.Contains(val, find)
}

func joinPath(path []string) string {
	return strings.Join(path, ".")
}

func isURL(path string) bool {
	return strings.HasPrefix(path, "http://") || strings.HasPrefix(path, "https://")
}
