package main

import (
	"fmt"
	"io"
	"strings"

	"gopkg.in/yaml.v3"
)

func walk(node *yaml.Node, path []string, out io.Writer, remain int) {

	// Node is empty, do not include empty values
	if !includeEmpty && isEmptyNode(node) {
		return
	}

	switch node.Kind {

	case yaml.MappingNode: // YAML object
		if remain == 0 {
			fmt.Fprintf(out, "%s: <object>\n", strings.Join(path, "."))
			return
		}

		nextRem := remain
		if remain > 0 {
			nextRem = remain - 1
		}

		for i := 0; i < len(node.Content); i += 2 {
			keyNode := node.Content[i]
			valueNode := node.Content[i+1]

			// Skip the ladder
			if pure && autoGeneratedField[keyNode.Value] {
				continue
			}

			walk(valueNode, append(path, keyNode.Value), out, nextRem)
		}

	case yaml.SequenceNode: // YAML list: arr[0], arr[1], ...
		if remain == 0 {
			fmt.Fprintf(out, "%s: <array>\n", strings.Join(path, "."))
			return
		}

		nextRem := remain
		if remain > 0 {
			nextRem = remain - 1
		}

		for i, item := range node.Content {
			p := make([]string, len(path))
			copy(p, path)
			p[len(p)-1] += fmt.Sprintf("[%d]", i)
			walk(item, p, out, nextRem)
		}

	default: // reached a scaler value (tail)
		// If the scalar contains newlines or was originally a block scalar, preserve it as a literal block.
		val := node.Value
		if node.Kind == yaml.ScalarNode && (strings.Contains(val, "\n") || node.Style == yaml.LiteralStyle || node.Style == yaml.FoldedStyle) {
			lines := strings.Split(val, "\n")
			joined := strings.Join(lines, "\n")

			// --grep
			if !matchGrep(joined) {
				return
			}

			fmt.Fprintf(out, "%s: |-\n", strings.Join(path, "."))

			for i, line := range lines {
				// avoid printing an extra trailing line when Split yields a trailing empty string
				// but keep exact line breaks otherwise
				if i == len(lines)-1 && line == "" {
					continue
				}
				fmt.Fprintf(out, "  %s\n", line)
			}
			return
		}

		// For single-line scalars that include YAML-sensitive characters, emit a quoted value.
		if strings.ContainsAny(val, ":[]{},") || strings.HasPrefix(val, " ") || strings.HasSuffix(val, " ") {
			// --grep
			if !matchGrep(val) {
				return
			}

			escaped := strings.ReplaceAll(val, "\"", "\\\"")
			fmt.Fprintf(out, "%s: \"%s\"\n", strings.Join(path, "."), escaped)
			return
		}

		// --grep
		if !matchGrep(val) {
			return
		}

		line := fmt.Sprintf("%s: %s", strings.Join(path, "."), val)
		fmt.Fprintln(out, line)
	}
}