apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: walk
spec:
  version: "v1.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/HarshPanchal18/kubectl-walk/releases/download/v1.1.0/kubectl-walk-linux-amd64.tar.gz
    sha256: "b2913a8ba4a7ce90cadd91c1e5f3ef199fe8e4a728af8170575d331ed07eb132"
    bin: kubectl-walk-linux-amd64
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/HarshPanchal18/kubectl-walk/releases/download/v1.1.0/kubectl-walk-darwin-amd64.tar.gz
    sha256: "597dd1364ef1c1c811bf3adba621007705109a0557176f4d7ad8416fe7fd98f0"
    bin: kubectl-walk-darwin-amd64
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/HarshPanchal18/kubectl-walk/releases/download/v1.1.0/kubectl-walk-darwin-arm64.tar.gz
    sha256: "9157904d94e457e91fa83a568da4f757567239338922b23c7434f62ed8bce028"
    bin: kubectl-walk-darwin-arm64
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/HarshPanchal18/kubectl-walk/releases/download/v1.1.0/kubectl-walk-windows-amd64.zip
    sha256: "73a5f4f09a62edd7a880cdd61d0278b7eddd8b7ad6b136e7b6236735d2a560c5"
    bin: kubectl-walk-windows-amd64.exe
  shortDescription: "Explore Kubernetes YAML like a human — not like a machine"
  description: |
    kubectl-walk helps you to flatten, filters, and visualizes nested fields of Kubernetes objects or YAML files.
  homepage: https://github.com/HarshPanchal18/kubectl-walk