package main

import (
	"fmt"
	"io"
	"strings"

	"gopkg.in/yaml.v3"
)

func walk(node *yaml.Node, path []string, out io.Writer, remain int) {

	// Node is empty, do not include empty values
	if !includeEmpty && isEmptyNode(node) {
		return
	}

	switch node.Kind {

	case yaml.MappingNode: // YAML object
		if remain == 0 {
			fmt.Fprintf(out, "%s: <object>\n", joinPath(path))
			return
		}

		nextRem := remain
		if remain > 0 {
			nextRem = remain - 1
		}

		for i := 0; i < len(node.Content); i += 2 {
			keyNode := node.Content[i]
			valueNode := node.Content[i+1]

			// Skip the ladder
			if pure && autoGeneratedField[keyNode.Value] {
				continue
			}

			walk(valueNode, append(path, keyNode.Value), out, nextRem)
		}

	case yaml.SequenceNode: // YAML list: arr[0], arr[1], ...
		if remain == 0 {
			fmt.Fprintf(out, "%s: <array>\n", joinPath(path))
			return
		}

		nextRem := remain
		if remain > 0 {
			nextRem = remain - 1
		}

		for i, item := range node.Content {
			p := append([]string{}, path...)
			p[len(p)-1] += fmt.Sprintf("[%d]", i)
			walk(item, p, out, nextRem)
		}

	default: // reached a scaler value (tail)

		val:= node.Value
		key := strings.Join(path, ".")

		if valuesOnly {
			if node.Kind == yaml.ScalarNode {
				val := node.Value

				if !findKey(key) || !matchGrep(val) {
					return
				}

				fmt.Fprintln(out, val)
			}
			return
		}

		// --find
		if !findKey(key) {
			return
		}

		// Line to print
		var line string

		// If the scalar contains newlines or was originally a block scalar, preserve it as a literal block.
		if node.Kind == yaml.ScalarNode && (strings.Contains(val, "\n") || node.Style == yaml.LiteralStyle || node.Style == yaml.FoldedStyle) {
			// --grep
			if !matchGrep(val) {
				return
			}

			line = fmt.Sprintf("%s: |-\n", joinPath(path))
			fmt.Fprintln(out, line)

			lines := strings.Split(val, "\n")

			for i, line := range lines {
				// avoid printing an extra trailing line when Split yields a trailing empty string
				// but keep exact line breaks otherwise
				if i == len(lines)-1 && line == "" {
					continue
				}
				fmt.Fprintf(out, "  %s\n", line)
			}
			return
		}

		// For single-line scalars that include YAML-sensitive characters, emit a quoted value.
		if strings.ContainsAny(val, ":[]{},") || strings.HasPrefix(val, " ") || strings.HasSuffix(val, " ") {
			// --grep
			if !matchGrep(val) {
				return
			}

			// --keys
			if keysOnly {
				line = joinPath(path)
				fmt.Fprintln(out, line)
				return
			}

			escapedValue := strings.ReplaceAll(val, "\"", "\\\"")
			line = fmt.Sprintf("%s: \"%s\"", joinPath(path), escapedValue)
			fmt.Fprintln(out, line)
			return
		}

		// --grep
		if !matchGrep(val) {
			return
		}

		// --keys
		if keysOnly {
			line = joinPath(path)
			fmt.Fprintln(out, line)
			return
		}

		line = fmt.Sprintf("%s: %s", joinPath(path), val)
		fmt.Fprintln(out, line)
	}
}

func walkTree(node *yaml.Node, prefix string, out io.Writer) {

	switch node.Kind {

	case yaml.MappingNode:

		count := len(node.Content) / 2
		for i := 0; i < len(node.Content); i += 2 {

			k := node.Content[i].Value
			v := node.Content[i+1]

			if pure && autoGeneratedField[k] {
				continue
			}

			last := (i/2) == count - 1

			connector := "├── "
			nextPrefix := prefix + "│   "

			if last {
				connector = "└── "
				nextPrefix = prefix + "    "
			}

			if keysOnly {
				fmt.Fprintf(out, "%s%s%s\n", prefix, connector, k)
			} else {
				fmt.Fprintf(out, "%s%s%s = %s\n", prefix, connector, k, v.Value)
			}

			walkTree(v, nextPrefix, out)
		}

	case yaml.SequenceNode:

		for i, item := range node.Content {

			last := i == len(node.Content) - 1

			connector := "├── "
			nextPrefix := prefix + "│   "

			if last {
				connector = "└── "
				nextPrefix = prefix + "    "
			}

			fmt.Fprintf(out, "%s%s[%d]\n", prefix, connector, i)
			walkTree(item, nextPrefix, out)
		}
	}
}